import asyncio
from datetime import UTC, datetime, timedelta

from sqlalchemy import select

from app.core.config import settings
from app.core.security import hash_password
from app.db.session import AsyncSessionLocal
from app.models.domain import Event, Place, PlaceKind, Restaurant, User, UserRole
from app.services.food_catalog import FOOD_CATALOG


PLACES = [
    {
        "name": "Charminar",
        "slug": "charminar",
        "kind": PlaceKind.monument,
        "short_description": "Iconic 1591 monument surrounded by Laad Bazaar and food lanes.",
        "history": "Built by Muhammad Quli Qutb Shah, Charminar anchors Hyderabad's Old City heritage district.",
        "address": "Char Kaman, Ghansi Bazaar",
        "latitude": 17.3616,
        "longitude": 78.4747,
        "timings": {"open": "09:30", "close": "17:30"},
        "entry_fee": {"indian": 25, "foreigner": 300},
        "best_time_to_visit": "Early morning or evening",
        "accessibility": {"summary": "Outer plaza is easier than upper monument levels."},
        "safety": {"score": 82, "note": "High-footfall zone; use marked pickup points at night."},
        "ai_tips": ["Pair with Laad Bazaar", "Use metro plus auto during peak traffic"],
        "rating": 4.8,
        "review_count": 12400,
        "is_featured": True,
    },
    {
        "name": "Golconda Fort",
        "slug": "golconda-fort",
        "kind": PlaceKind.monument,
        "short_description": "Historic fort complex with acoustic architecture and sunset views.",
        "history": "Golconda Fort grew under the Qutb Shahi dynasty and is tied to the region's diamond trade history.",
        "address": "Ibrahim Bagh",
        "latitude": 17.3833,
        "longitude": 78.4011,
        "timings": {"open": "09:00", "close": "17:30"},
        "entry_fee": {"indian": 25, "foreigner": 300},
        "best_time_to_visit": "Late afternoon",
        "accessibility": {"summary": "Steep climbs; lower ramparts are the easiest section."},
        "safety": {"score": 86, "note": "Carry water and avoid isolated edges after dark."},
        "ai_tips": ["Wear walking shoes", "Reserve time for Qutb Shahi Tombs"],
        "rating": 4.7,
        "review_count": 9300,
        "is_featured": True,
    },
    {
        "name": "Hussain Sagar",
        "slug": "hussain-sagar",
        "kind": PlaceKind.lake,
        "short_description": "Lakefront promenade connecting Hyderabad and Secunderabad.",
        "history": "The lake was built during the Qutb Shahi period and remains a central evening destination.",
        "address": "Tank Bund Road",
        "latitude": 17.4239,
        "longitude": 78.4738,
        "timings": {"open": "06:00", "close": "22:00"},
        "entry_fee": {"general": 0},
        "best_time_to_visit": "Evening",
        "accessibility": {"summary": "Good promenade access and seating."},
        "safety": {"score": 88, "note": "Prefer busy stretches and planned cab pickup points."},
        "ai_tips": ["Check Tank Bund traffic", "Good for family walks"],
        "rating": 4.5,
        "review_count": 8100,
        "is_featured": True,
    },
    {
        "name": "Durgam Cheruvu",
        "slug": "durgam-cheruvu",
        "kind": PlaceKind.lake,
        "short_description": "West Hyderabad lakefront with cable bridge views and cafe access.",
        "history": "Once called the Secret Lake, this area is now a major evening and bridge-view destination.",
        "address": "Madhapur",
        "latitude": 17.4307,
        "longitude": 78.3896,
        "timings": {"open": "06:00", "close": "22:00"},
        "entry_fee": {"general": 0},
        "best_time_to_visit": "Sunset",
        "accessibility": {"summary": "Lakefront paths are accessible in many sections."},
        "safety": {"score": 88, "note": "Plan pickup away from bridge traffic at night."},
        "ai_tips": ["Pair with HITEC City dining", "Best for sunset and night views"],
        "rating": 4.4,
        "review_count": 4200,
        "is_featured": True,
    },
    {
        "name": "KBR National Park",
        "slug": "kbr-national-park",
        "kind": PlaceKind.hidden_gem,
        "short_description": "Urban forest trail for morning walks in Jubilee Hills.",
        "history": "The park protects a large green lung in the middle of Hyderabad's west-side neighborhoods.",
        "address": "Jubilee Hills",
        "latitude": 17.4239,
        "longitude": 78.4214,
        "timings": {"open": "05:30", "close": "18:30"},
        "entry_fee": {"general": 40},
        "best_time_to_visit": "Early morning",
        "accessibility": {"summary": "Outer walking track is easier than inner trail sections."},
        "safety": {"score": 91, "note": "Use marked walking routes and daylight hours."},
        "ai_tips": ["Good fitness stop", "Pair with Jubilee Hills cafes"],
        "rating": 4.5,
        "review_count": 5300,
        "is_featured": True,
    },
    {
        "name": "Paigah Tombs",
        "slug": "paigah-tombs",
        "kind": PlaceKind.hidden_gem,
        "short_description": "Quiet heritage complex known for delicate stucco and lattice work.",
        "history": "The Paigah nobles were influential Hyderabad aristocrats, and their tombs preserve a distinct architectural style.",
        "address": "Santoshnagar",
        "latitude": 17.3424,
        "longitude": 78.5006,
        "timings": {"open": "10:00", "close": "17:00"},
        "entry_fee": {"general": 0},
        "best_time_to_visit": "Morning",
        "accessibility": {"summary": "Uneven heritage paths; comfortable footwear helps."},
        "safety": {"score": 84, "note": "Visit in daylight and use a planned cab pickup."},
        "ai_tips": ["Good for architecture lovers", "Pair with Old City heritage"],
        "rating": 4.4,
        "review_count": 1600,
        "is_featured": False,
    },
    {
        "name": "Shilparamam",
        "slug": "shilparamam",
        "kind": PlaceKind.market,
        "short_description": "Craft village with handmade goods, food stalls, and cultural performances.",
        "history": "Built as a cultural village, Shilparamam showcases crafts and folk arts from Telangana and beyond.",
        "address": "Madhapur",
        "latitude": 17.4526,
        "longitude": 78.3762,
        "timings": {"open": "10:30", "close": "20:30"},
        "entry_fee": {"general": 60},
        "best_time_to_visit": "Evening",
        "accessibility": {"summary": "Mostly open paths with some uneven craft-stall areas."},
        "safety": {"score": 88, "note": "Crowded during festivals; keep pickup points clear."},
        "ai_tips": ["Check cultural event schedules", "Carry cash for small stalls"],
        "rating": 4.4,
        "review_count": 6100,
        "is_featured": True,
    },
    {
        "name": "Ramoji Film City",
        "slug": "ramoji-film-city",
        "kind": PlaceKind.experience,
        "short_description": "Large film studio and family theme-park day trip.",
        "history": "Ramoji Film City is one of India's best-known film studio campuses and a major tourist attraction.",
        "address": "Abdullapurmet",
        "latitude": 17.2543,
        "longitude": 78.6808,
        "timings": {"open": "09:00", "close": "17:30"},
        "entry_fee": {"general": 1350},
        "best_time_to_visit": "Full day",
        "accessibility": {"summary": "Managed shuttles and paved guest zones in many areas."},
        "safety": {"score": 88, "note": "Book tickets early and follow shuttle instructions."},
        "ai_tips": ["Keep a full day", "Good for families and groups"],
        "rating": 4.6,
        "review_count": 11800,
        "is_featured": True,
    },
    {
        "name": "Chilkur Balaji Temple",
        "slug": "chilkur-balaji-temple",
        "kind": PlaceKind.temple,
        "short_description": "Popular devotional temple near Osman Sagar, often called Visa Balaji.",
        "history": "Chilkur Balaji is a well-known temple on the city outskirts with long-standing local traditions.",
        "address": "Chilkur",
        "latitude": 17.3587,
        "longitude": 78.3008,
        "timings": {"open": "05:00", "close": "20:00"},
        "entry_fee": {"general": 0},
        "best_time_to_visit": "Early morning",
        "accessibility": {"summary": "Queues can be long; avoid peak weekends with elders."},
        "safety": {"score": 86, "note": "Keep footwear and bags simple during crowd hours."},
        "ai_tips": ["Pair with Gandipet", "Go early on weekends"],
        "rating": 4.7,
        "review_count": 9800,
        "is_featured": True,
    },
    {
        "name": "Taj Falaknuma Palace",
        "slug": "taj-falaknuma-palace",
        "kind": PlaceKind.resort,
        "short_description": "Luxury palace hotel experience with dining and heritage views.",
        "history": "Falaknuma Palace was a Nizam-era palace and now operates as a luxury heritage hotel.",
        "address": "Falaknuma",
        "latitude": 17.3301,
        "longitude": 78.4675,
        "timings": {"open": "00:00", "close": "23:59"},
        "entry_fee": {"dining_from": 3500},
        "best_time_to_visit": "Evening",
        "accessibility": {"summary": "Managed property access; confirm requirements while booking."},
        "safety": {"score": 92, "note": "Reservation rules and dress codes may apply."},
        "ai_tips": ["Reserve high tea or dinner", "Good luxury experience"],
        "rating": 4.7,
        "review_count": 4700,
        "is_featured": False,
    },
    {
        "name": "Moula Ali Dargah",
        "slug": "moula-ali-dargah",
        "kind": PlaceKind.mosque,
        "short_description": "Hilltop shrine with a heritage climb and city views.",
        "history": "Moula Ali is one of the oldest sacred hill landmarks in the Secunderabad region.",
        "address": "Moula Ali",
        "latitude": 17.4664,
        "longitude": 78.5604,
        "timings": {"open": "06:00", "close": "20:00"},
        "entry_fee": {"general": 0},
        "best_time_to_visit": "Early morning",
        "accessibility": {"summary": "Steep steps and hill terrain; not suitable for limited mobility."},
        "safety": {"score": 84, "note": "Avoid peak afternoon heat and isolated late climbs."},
        "ai_tips": ["Wear comfortable footwear", "Best for morning views"],
        "rating": 4.5,
        "review_count": 2400,
        "is_featured": False,
    },
    {
        "name": "Sanjeevaiah Park",
        "slug": "sanjeevaiah-park",
        "kind": PlaceKind.hidden_gem,
        "short_description": "Lakefront park near Necklace Road for family walks and evening lawns.",
        "history": "Sanjeevaiah Park is one of the city's older green spaces around the Hussain Sagar lakefront.",
        "address": "Necklace Road",
        "latitude": 17.4322,
        "longitude": 78.4731,
        "timings": {"open": "08:00", "close": "19:00"},
        "entry_fee": {"general": 20},
        "best_time_to_visit": "Evening",
        "accessibility": {"summary": "Broad park paths with lakefront sections and seating."},
        "safety": {"score": 88, "note": "Prefer active park sections and planned pickup points."},
        "ai_tips": ["Pair with Necklace Road", "Good budget family stop"],
        "rating": 4.3,
        "review_count": 3300,
        "is_featured": False,
    },
    {
        "name": "NTR Gardens",
        "slug": "ntr-gardens",
        "kind": PlaceKind.experience,
        "short_description": "Family garden near Hussain Sagar with kids activities and short rides.",
        "history": "NTR Gardens is part of the lakefront tourism circuit around Necklace Road and Lumbini Park.",
        "address": "Necklace Road",
        "latitude": 17.4128,
        "longitude": 78.4697,
        "timings": {"open": "12:30", "close": "20:30"},
        "entry_fee": {"general": 20},
        "best_time_to_visit": "Evening",
        "accessibility": {"summary": "Garden paths are easier than activity sections."},
        "safety": {"score": 86, "note": "Watch children around ride and crowd areas."},
        "ai_tips": ["Pair with Lumbini Park", "Good for kids near Tank Bund"],
        "rating": 4.2,
        "review_count": 5100,
        "is_featured": False,
    },
    {
        "name": "Ocean Park",
        "slug": "ocean-park-hyderabad",
        "kind": PlaceKind.experience,
        "short_description": "Water park and family ride zone on the Gandipet side.",
        "history": "Ocean Park has long served as a family amusement destination on Hyderabad's western outskirts.",
        "address": "Gandipet Road",
        "latitude": 17.3854,
        "longitude": 78.3217,
        "timings": {"open": "11:00", "close": "18:00"},
        "entry_fee": {"general": 650},
        "best_time_to_visit": "Morning",
        "accessibility": {"summary": "Ride access varies by height, age, and safety rules."},
        "safety": {"score": 84, "note": "Water zones require close child supervision."},
        "ai_tips": ["Carry swimwear", "Return before late rural-road hours"],
        "rating": 4.0,
        "review_count": 3900,
        "is_featured": False,
    },
    {
        "name": "Karmanghat Hanuman Temple",
        "slug": "karmanghat-hanuman-temple",
        "kind": PlaceKind.temple,
        "short_description": "Historic Hanuman temple in east Hyderabad with strong local devotion.",
        "history": "Karmanghat Hanuman Temple is among the city's older and most visited local temples.",
        "address": "Karmanghat",
        "latitude": 17.3396,
        "longitude": 78.5322,
        "timings": {"open": "06:00", "close": "21:00"},
        "entry_fee": {"general": 0},
        "best_time_to_visit": "Early morning",
        "accessibility": {"summary": "Crowded queue areas during Tuesdays and Saturdays."},
        "safety": {"score": 86, "note": "Parking and queues get dense at peak darshan times."},
        "ai_tips": ["Go early on peak days", "Good east-side temple stop"],
        "rating": 4.7,
        "review_count": 7600,
        "is_featured": False,
    },
    {
        "name": "Balkampet Yellamma Temple",
        "slug": "balkampet-yellamma-temple",
        "kind": PlaceKind.temple,
        "short_description": "Popular city temple known for local festivals and devotional footfall.",
        "history": "The temple is a major local devotional landmark in the Balkampet area.",
        "address": "Balkampet",
        "latitude": 17.4461,
        "longitude": 78.4482,
        "timings": {"open": "06:00", "close": "20:30"},
        "entry_fee": {"general": 0},
        "best_time_to_visit": "Morning",
        "accessibility": {"summary": "Busy temple lanes; easier outside festival rush."},
        "safety": {"score": 86, "note": "Use metro or cab during crowded festival periods."},
        "ai_tips": ["Avoid peak festival crowds", "Good central devotional stop"],
        "rating": 4.6,
        "review_count": 6100,
        "is_featured": False,
    },
    {
        "name": "Telangana State Archaeology Museum",
        "slug": "telangana-state-archaeology-museum",
        "kind": PlaceKind.experience,
        "short_description": "Indoor museum stop with archaeology, sculpture, and regional history galleries.",
        "history": "The museum in Public Gardens preserves archaeological and artistic material from the region.",
        "address": "Public Gardens",
        "latitude": 17.3994,
        "longitude": 78.4693,
        "timings": {"open": "10:30", "close": "17:00"},
        "entry_fee": {"general": 20},
        "best_time_to_visit": "Late morning",
        "accessibility": {"summary": "Indoor museum access with older-building constraints in some sections."},
        "safety": {"score": 89, "note": "Rain-safe and family-friendly daytime stop."},
        "ai_tips": ["Pair with Birla Mandir", "Good indoor history stop"],
        "rating": 4.3,
        "review_count": 2600,
        "is_featured": False,
    },
    {
        "name": "Bhongir Fort",
        "slug": "bhongir-fort",
        "kind": PlaceKind.getaway,
        "short_description": "Rock hill fort day trip with trekking and panoramic views.",
        "history": "Bhongir Fort sits on a monolithic rock and is tied to medieval Deccan fort history.",
        "address": "Bhuvanagiri",
        "latitude": 17.5153,
        "longitude": 78.8859,
        "timings": {"open": "10:00", "close": "17:00"},
        "entry_fee": {"general": 20},
        "best_time_to_visit": "Winter morning",
        "accessibility": {"summary": "Rocky climb; not suitable for limited mobility."},
        "safety": {"score": 80, "note": "Avoid rain, heat, and cliff-edge shortcuts."},
        "ai_tips": ["Wear grip shoes", "Start early for the climb"],
        "rating": 4.4,
        "review_count": 3400,
        "is_featured": False,
    },
    {
        "name": "Pochampally",
        "slug": "pochampally",
        "kind": PlaceKind.getaway,
        "short_description": "Ikat weaving village day trip for textile shopping and craft discovery.",
        "history": "Pochampally is known for ikat weaving and textile craft traditions near Hyderabad.",
        "address": "Yadadri district",
        "latitude": 17.3473,
        "longitude": 78.8242,
        "timings": {"open": "09:00", "close": "18:00"},
        "entry_fee": {"general": 0},
        "best_time_to_visit": "Morning",
        "accessibility": {"summary": "Village lanes and shop access vary."},
        "safety": {"score": 84, "note": "Use a planned cab loop and daylight shopping hours."},
        "ai_tips": ["Buy textiles directly from weaving stores", "Pair with Yadadri if time allows"],
        "rating": 4.4,
        "review_count": 1800,
        "is_featured": False,
    },
]

RESTAURANTS = [
    {"name": "Hotel Shadab", "cuisine": ["Hyderabadi", "Biryani", "Haleem"], "price_band": "mid", "rating": 4.4, "cost_for_two": 900, "address": "Ghansi Bazaar", "latitude": 17.3687, "longitude": 78.4772, "crowd_level": "very_high", "open_late": True, "highlights": ["mutton biryani", "haleem", "kebabs"]},
    {"name": "Hotel Nayaab", "cuisine": ["Hyderabadi", "Breakfast", "Biryani"], "price_band": "budget", "rating": 4.3, "cost_for_two": 700, "address": "Chatta Bazaar", "latitude": 17.3692, "longitude": 78.4748, "crowd_level": "very_high", "open_late": True, "highlights": ["nihari", "paya", "biryani"]},
    {"name": "Pista House", "cuisine": ["Hyderabadi", "Haleem", "Bakery"], "price_band": "mid", "rating": 4.3, "cost_for_two": 850, "address": "Shah Ali Banda", "latitude": 17.3578, "longitude": 78.4733, "crowd_level": "high", "open_late": True, "highlights": ["haleem", "biryani", "bakery sweets"]},
    {"name": "Cafe Bahar", "cuisine": ["Hyderabadi", "Biryani", "Irani Chai"], "price_band": "mid", "rating": 4.4, "cost_for_two": 800, "address": "Basheerbagh", "latitude": 17.3999, "longitude": 78.4806, "crowd_level": "high", "open_late": True, "highlights": ["Hyderabadi biryani", "Irani chai", "haleem"]},
    {"name": "Grand Hotel", "cuisine": ["Hyderabadi", "Biryani", "Bakery"], "price_band": "budget", "rating": 4.1, "cost_for_two": 750, "address": "Abids", "latitude": 17.3897, "longitude": 78.4763, "crowd_level": "high", "open_late": True, "highlights": ["biryani", "Irani cafe snacks", "bakery"]},
    {"name": "Mehfil", "cuisine": ["Hyderabadi", "Biryani", "Tandoori"], "price_band": "budget", "rating": 4.2, "cost_for_two": 700, "address": "Narayanaguda", "latitude": 17.3992, "longitude": 78.4891, "crowd_level": "very_high", "open_late": True, "highlights": ["biryani", "tandoori", "late-night meals"]},
    {"name": "Bawarchi", "cuisine": ["Hyderabadi", "Biryani", "Grill"], "price_band": "mid", "rating": 4.2, "cost_for_two": 850, "address": "RTC X Roads", "latitude": 17.4064, "longitude": 78.4968, "crowd_level": "very_high", "open_late": True, "highlights": ["Hyderabadi biryani", "grill", "takeaway"]},
    {"name": "Paradise Biryani", "cuisine": ["Hyderabadi", "Biryani"], "price_band": "mid", "rating": 4.2, "cost_for_two": 900, "address": "Paradise Circle, Secunderabad", "latitude": 17.4419, "longitude": 78.4873, "crowd_level": "high", "open_late": True, "highlights": ["Hyderabadi biryani", "kebabs", "family seating"]},
    {"name": "Shah Ghouse", "cuisine": ["Hyderabadi", "Biryani", "Haleem"], "price_band": "mid", "rating": 4.3, "cost_for_two": 800, "address": "Tolichowki", "latitude": 17.3991, "longitude": 78.4149, "crowd_level": "high", "open_late": True, "highlights": ["biryani", "haleem", "kebabs"]},
    {"name": "Cafe Niloufer", "cuisine": ["Irani Chai", "Cafe", "Bakery"], "price_band": "budget", "rating": 4.5, "cost_for_two": 450, "address": "Lakdikapul", "latitude": 17.4046, "longitude": 78.4623, "crowd_level": "very_high", "open_late": True, "highlights": ["Irani chai", "bun maska", "Osmania biscuits"]},
    {"name": "Nimrah Cafe", "cuisine": ["Irani Chai", "Bakery"], "price_band": "budget", "rating": 4.5, "cost_for_two": 250, "address": "Charminar", "latitude": 17.3618, "longitude": 78.4748, "crowd_level": "very_high", "open_late": True, "highlights": ["Irani chai", "Osmania biscuits", "Ramzan walk"]},
    {"name": "Karachi Bakery", "cuisine": ["Bakery", "Desserts"], "price_band": "budget", "rating": 4.4, "cost_for_two": 500, "address": "Mozamjahi Market", "latitude": 17.3849, "longitude": 78.4748, "crowd_level": "high", "open_late": False, "highlights": ["fruit biscuits", "plum cake", "souvenirs"]},
    {"name": "Subhan Bakery", "cuisine": ["Bakery", "Biscuits"], "price_band": "budget", "rating": 4.4, "cost_for_two": 350, "address": "Nampally", "latitude": 17.388, "longitude": 78.4677, "crowd_level": "high", "open_late": False, "highlights": ["Osmania biscuits", "puffs", "plum cake"]},
    {"name": "Pragati Tiffins", "cuisine": ["South Indian", "Tiffins"], "price_band": "budget", "rating": 4.3, "cost_for_two": 250, "address": "Koti", "latitude": 17.3859, "longitude": 78.4867, "crowd_level": "very_high", "open_late": False, "highlights": ["idli", "upma", "dosa"]},
    {"name": "Taj Mahal Hotel", "cuisine": ["South Indian", "Vegetarian"], "price_band": "budget", "rating": 4.2, "cost_for_two": 600, "address": "Abids", "latitude": 17.3918, "longitude": 78.4753, "crowd_level": "high", "open_late": False, "highlights": ["tiffins", "meals", "filter coffee"]},
    {"name": "Ram Ki Bandi", "cuisine": ["Street Food", "Dosa"], "price_band": "budget", "rating": 4.4, "cost_for_two": 250, "address": "Nampally", "latitude": 17.3875, "longitude": 78.4702, "crowd_level": "very_high", "open_late": True, "highlights": ["dosa", "cheese dosa", "late-night tiffins"]},
    {"name": "Gokul Chaat", "cuisine": ["Street Food", "Chaat"], "price_band": "budget", "rating": 4.2, "cost_for_two": 250, "address": "Koti", "latitude": 17.386, "longitude": 78.4815, "crowd_level": "very_high", "open_late": False, "highlights": ["chaat", "pani puri", "dahi puri"]},
    {"name": "Chutneys", "cuisine": ["South Indian", "Vegetarian"], "price_band": "mid", "rating": 4.3, "cost_for_two": 700, "address": "Banjara Hills", "latitude": 17.4141, "longitude": 78.4487, "crowd_level": "high", "open_late": False, "highlights": ["dosa", "idli", "family dining"]},
    {"name": "Roastery Coffee House", "cuisine": ["Cafe", "Coffee", "Desserts"], "price_band": "mid", "rating": 4.5, "cost_for_two": 1200, "address": "Banjara Hills", "latitude": 17.4155, "longitude": 78.4341, "crowd_level": "moderate", "open_late": False, "highlights": ["specialty coffee", "brunch", "desserts"]},
    {"name": "Olive Bistro", "cuisine": ["Fine Dining", "Mediterranean"], "price_band": "premium", "rating": 4.4, "cost_for_two": 3200, "address": "Jubilee Hills", "latitude": 17.4302, "longitude": 78.3985, "crowd_level": "moderate", "open_late": False, "highlights": ["Mediterranean", "lake view", "date night"]},
]

RESTAURANTS = [
    {
        "name": item.name,
        "cuisine": item.cuisine,
        "price_band": item.price_band,
        "rating": item.rating,
        "cost_for_two": item.cost_for_two,
        "address": item.address,
        "latitude": item.latitude,
        "longitude": item.longitude,
        "crowd_level": item.crowd_level,
        "open_late": item.open_late,
        "highlights": item.highlights,
    }
    for item in FOOD_CATALOG
]

EVENTS = [
    {
        "title": "Shilparamam Craft Bazaar",
        "event_type": "exhibition",
        "description": "Craft, textile, food, and cultural stalls in Madhapur.",
        "days_from_now": 7,
        "duration_hours": 6,
        "venue": "Shilparamam, Madhapur",
        "latitude": 17.4526,
        "longitude": 78.3762,
        "ticket_price": 60,
    },
    {
        "title": "Golconda Sound and Light Show",
        "event_type": "heritage_show",
        "description": "Evening storytelling experience inside the Golconda heritage circuit.",
        "days_from_now": 3,
        "duration_hours": 2,
        "venue": "Golconda Fort",
        "latitude": 17.3833,
        "longitude": 78.4011,
        "ticket_price": 120,
    },
    {
        "title": "Tank Bund Sunday Funday",
        "event_type": "family_street_event",
        "description": "Family-friendly lakefront activity window with snacks, music, and walking space.",
        "days_from_now": 5,
        "duration_hours": 4,
        "venue": "Tank Bund",
        "latitude": 17.4239,
        "longitude": 78.4738,
        "ticket_price": 0,
    },
]


async def seed() -> None:
    if not settings.seed_demo_data:
        return

    async with AsyncSessionLocal() as session:
        for data in PLACES:
            existing = await session.execute(select(Place).where(Place.slug == data["slug"]))
            if not existing.scalar_one_or_none():
                session.add(Place(**data))

        for data in RESTAURANTS:
            existing = await session.execute(select(Restaurant).where(Restaurant.name == data["name"]))
            if not existing.scalar_one_or_none():
                session.add(Restaurant(**data))

        now = datetime.now(UTC)
        for data in EVENTS:
            event_exists = await session.execute(select(Event).where(Event.title == data["title"]))
            if not event_exists.scalar_one_or_none():
                starts_at = now + timedelta(days=data["days_from_now"])
                session.add(
                    Event(
                        title=data["title"],
                        event_type=data["event_type"],
                        description=data["description"],
                        starts_at=starts_at,
                        ends_at=starts_at + timedelta(hours=data["duration_hours"]),
                        venue=data["venue"],
                        latitude=data["latitude"],
                        longitude=data["longitude"],
                        ticket_price=data["ticket_price"],
                    )
                )

        admin_exists = await session.execute(select(User).where(User.email == settings.seed_admin_email))
        if not admin_exists.scalar_one_or_none():
            session.add(
                User(
                    email=settings.seed_admin_email,
                    full_name="Explore Hyderabad Admin",
                    password_hash=hash_password(settings.seed_admin_password),
                    role=UserRole.admin,
                    preferred_language="en",
                    interests=["operations"],
                )
            )

        await session.commit()

        from app.services.rag import rag_service

        await rag_service.reindex(session, include_embeddings=False)


if __name__ == "__main__":
    asyncio.run(seed())
