import { Landmark, Map, ShieldCheck, Sparkles, Train, Utensils } from "lucide-react";

export type Place = {
  slug: string;
  name: string;
  type: string;
  category: string;
  image: string;
  rating: string;
  meta: string;
  tip: string;
  lat: number;
  lng: number;
  distanceKm: number;
  durationHours: number;
  fee: number;
  crowd: "Low" | "Moderate" | "High" | "Very high";
  safetyScore: number;
  accessibility: string;
  bestTime: string;
  tags: string[];
};

export type FoodSpot = {
  name: string;
  category: "Biryani" | "Street food" | "Cafe" | "Rooftop" | "Midnight" | "Fine dining" | "South Indian" | "Bakery";
  area: string;
  costForTwo: number;
  rating: number;
  crowd: "Low" | "Moderate" | "High" | "Very high";
  openLate: boolean;
  distanceKm: number;
  specialties: string[];
  safetyNote: string;
};

export type EventItem = {
  title: string;
  date: string;
  type: string;
  venue: string;
  price: string;
};

export type MetroRoute = {
  from: string;
  to: string;
  line: string;
  interchange: string;
  duration: string;
  fare: string;
};

export const categories = [
  { label: "Monuments", icon: Landmark, color: "bg-lac", href: "/explore?category=Monuments" },
  { label: "Food", icon: Utensils, color: "bg-turmeric text-charcoal", href: "/food" },
  { label: "Metro", icon: Train, color: "bg-lake", href: "/planner?mode=metro" },
  { label: "AI Trips", icon: Sparkles, color: "bg-neem", href: "/planner" },
  { label: "Safety", icon: ShieldCheck, color: "bg-charcoal", href: "/explore?safe=true" },
  { label: "Nearby", icon: Map, color: "bg-lac", href: "/explore?nearby=true" }
];

const imageFor = {
  charminar: "/images/places/charminar.jpg",
  golcondaFort: "/images/places/golconda-fort.jpg",
  hussainSagar: "/images/places/hussain-sagar.jpg",
  salarJungMuseum: "/images/places/salar-jung-museum.jpg",
  laadBazaar: "/images/places/laad-bazaar.jpg",
  ananthagiriHills: "/images/places/ananthagiri-hills.jpg",
  ramojiFilmCity: "/images/places/ramoji-film-city.jpg",
  birlaMandir: "/images/places/birla-mandir.png",
  meccaMasjid: "/images/places/mecca-masjid.jpg",
  qutbShahiTombs: "/images/places/qutb-shahi-tombs.jpg",
  chowmahallaPalace: "/images/places/chowmahalla-palace.jpg",
  nehruZoologicalPark: "/images/places/nehru-zoological-park.jpg",
  shilparamam: "/images/places/shilparamam.jpg",
  inorbitMall: "/images/places/inorbit-mall.jpg",
  forumSujanaMall: "/images/places/forum-sujana-mall.jpg",
  sarathCityCapitalMall: "/images/places/sarath-city-capital-mall.jpg",
  prasadsMultiplex: "/images/places/prasads-multiplex.jpg",
  aaaCinemas: "/images/places/aaa-cinemas.jpg",
  wonderlaHyderabad: "/images/places/wonderla-hyderabad.jpg",
  gandipetPark: "/images/places/gandipet-park.jpg",
  tajFalaknumaPalace: "/images/places/taj-falaknuma-palace.jpg"
};

export const places: Place[] = [
  {
    slug: "charminar",
    name: "Charminar",
    type: "Heritage Monument",
    category: "Monuments",
    image: imageFor.charminar,
    rating: "4.8",
    meta: "Old City | Laad Bazaar | Ramzan food lanes",
    tip: "Visit before 9 AM or after 5 PM; combine with Mecca Masjid and Irani chai.",
    lat: 17.3616,
    lng: 78.4747,
    distanceKm: 4.2,
    durationHours: 2,
    fee: 25,
    crowd: "Very high",
    safetyScore: 82,
    accessibility: "Partial wheelchair access around outer plaza",
    bestTime: "Early morning",
    tags: ["history", "shopping", "street food", "mosque", "qr guide"]
  },
  {
    slug: "golconda-fort",
    name: "Golconda Fort",
    type: "Fort and Sound Show",
    category: "Monuments",
    image: imageFor.golcondaFort,
    rating: "4.7",
    meta: "Ibrahim Bagh | Sunset trail | Qutb Shahi Tombs",
    tip: "Carry water, start from the lower ramparts, and keep 2.5 hours for the climb.",
    lat: 17.3833,
    lng: 78.4011,
    distanceKm: 8.1,
    durationHours: 3,
    fee: 25,
    crowd: "High",
    safetyScore: 86,
    accessibility: "Steep climbs; limited accessibility beyond lower areas",
    bestTime: "Late afternoon",
    tags: ["history", "trekking", "sunset", "drone video", "ar preview"]
  },
  {
    slug: "hussain-sagar",
    name: "Hussain Sagar",
    type: "Lake and Promenade",
    category: "Lakes",
    image: imageFor.hussainSagar,
    rating: "4.5",
    meta: "Tank Bund | Necklace Road | Boat rides",
    tip: "Evening breeze is best; check traffic around Secretariat and Tank Bund.",
    lat: 17.4239,
    lng: 78.4738,
    distanceKm: 5.5,
    durationHours: 2,
    fee: 0,
    crowd: "Moderate",
    safetyScore: 88,
    accessibility: "Good promenade access and seating",
    bestTime: "Evening",
    tags: ["lake", "family", "nightlife", "metro", "weather"]
  },
  {
    slug: "salar-jung-museum",
    name: "Salar Jung Museum",
    type: "Museum",
    category: "Museums",
    image: imageFor.salarJungMuseum,
    rating: "4.6",
    meta: "Darulshifa | Art | Antiques | Families",
    tip: "Keep 2 hours and prioritize the clock gallery, sculptures, and textiles.",
    lat: 17.3713,
    lng: 78.4804,
    distanceKm: 3.7,
    durationHours: 2,
    fee: 50,
    crowd: "Moderate",
    safetyScore: 90,
    accessibility: "Elevators and indoor seating available",
    bestTime: "Late morning",
    tags: ["museum", "family", "indoor", "culture", "rain safe"]
  },
  {
    slug: "laad-bazaar",
    name: "Laad Bazaar",
    type: "Market",
    category: "Markets",
    image: imageFor.laadBazaar,
    rating: "4.4",
    meta: "Bangles | Pearls | Wedding shopping",
    tip: "Start from Charminar side and bargain politely; carry cash for small vendors.",
    lat: 17.3619,
    lng: 78.4738,
    distanceKm: 4.3,
    durationHours: 2,
    fee: 0,
    crowd: "Very high",
    safetyScore: 78,
    accessibility: "Narrow lanes; best with light bags",
    bestTime: "Before sunset",
    tags: ["shopping", "market", "bargaining", "pearls", "local"]
  },
  {
    slug: "ananthagiri-hills",
    name: "Ananthagiri Hills",
    type: "Weekend Getaway",
    category: "Weekend",
    image: imageFor.ananthagiriHills,
    rating: "4.3",
    meta: "Vikarabad | Forest trails | Coffee stops",
    tip: "Leave before 6 AM, avoid isolated trails after dark, and check rain forecasts.",
    lat: 17.3121,
    lng: 77.8633,
    distanceKm: 80,
    durationHours: 8,
    fee: 0,
    crowd: "Moderate",
    safetyScore: 80,
    accessibility: "Trail terrain; not wheelchair friendly",
    bestTime: "Monsoon mornings",
    tags: ["trekking", "weekend", "nature", "budget", "weather"]
  },
  {
    slug: "ramoji-film-city",
    name: "Ramoji Film City",
    type: "Film Studio Theme Park",
    category: "Theme Parks",
    image: imageFor.ramojiFilmCity,
    rating: "4.6",
    meta: "Abdullapurmet | Studio tours | Shows | Family day trip",
    tip: "Book tickets early, start before noon, and keep a full day for studio sets, shows, and shuttle transfers.",
    lat: 17.2543,
    lng: 78.6808,
    distanceKm: 34,
    durationHours: 8,
    fee: 1350,
    crowd: "High",
    safetyScore: 88,
    accessibility: "Managed shuttles and paved guest zones; check show seating access.",
    bestTime: "Full day",
    tags: ["ramoji", "film city", "theme park", "family", "shows", "studio", "kids"]
  },
  {
    slug: "birla-mandir",
    name: "Birla Mandir",
    type: "Temple",
    category: "Temples",
    image: imageFor.birlaMandir,
    rating: "4.7",
    meta: "Naubat Pahad | Marble temple | City view",
    tip: "Go around sunset for views; phones and bags may need to be deposited before entry.",
    lat: 17.4062,
    lng: 78.4691,
    distanceKm: 3.5,
    durationHours: 1.5,
    fee: 0,
    crowd: "High",
    safetyScore: 89,
    accessibility: "Steps and slopes; limited wheelchair access near upper sections.",
    bestTime: "Sunset",
    tags: ["temple", "viewpoint", "spiritual", "family", "free"]
  },
  {
    slug: "mecca-masjid",
    name: "Mecca Masjid",
    type: "Historic Mosque",
    category: "Mosques",
    image: imageFor.meccaMasjid,
    rating: "4.6",
    meta: "Old City | Charminar walk | Heritage precinct",
    tip: "Dress modestly, avoid prayer rush, and combine with Charminar and Laad Bazaar.",
    lat: 17.3604,
    lng: 78.4736,
    distanceKm: 4.1,
    durationHours: 1,
    fee: 0,
    crowd: "Very high",
    safetyScore: 82,
    accessibility: "Open courtyard access; busy lanes nearby.",
    bestTime: "Morning",
    tags: ["mosque", "heritage", "old city", "charminar", "culture"]
  },
  {
    slug: "qutb-shahi-tombs",
    name: "Qutb Shahi Tombs",
    type: "Heritage Tomb Complex",
    category: "Monuments",
    image: imageFor.qutbShahiTombs,
    rating: "4.5",
    meta: "Ibrahim Bagh | Near Golconda | Architecture",
    tip: "Pair with Golconda Fort and keep time for restored domes, gardens, and photography.",
    lat: 17.3951,
    lng: 78.3968,
    distanceKm: 8.6,
    durationHours: 2,
    fee: 20,
    crowd: "Moderate",
    safetyScore: 87,
    accessibility: "Garden paths are easier than inner tomb platforms.",
    bestTime: "Late afternoon",
    tags: ["tombs", "history", "architecture", "golconda", "photography"]
  },
  {
    slug: "chowmahalla-palace",
    name: "Chowmahalla Palace",
    type: "Palace Museum",
    category: "Museums",
    image: imageFor.chowmahallaPalace,
    rating: "4.5",
    meta: "Khilwat | Nizam heritage | Courtyards",
    tip: "Visit before Old City shopping; the vintage cars and durbar hall are highlights.",
    lat: 17.3578,
    lng: 78.4717,
    distanceKm: 4.6,
    durationHours: 2,
    fee: 100,
    crowd: "Moderate",
    safetyScore: 86,
    accessibility: "Courtyards are walkable; some heritage rooms have steps.",
    bestTime: "Late morning",
    tags: ["palace", "museum", "nizam", "old city", "heritage"]
  },
  {
    slug: "nehru-zoological-park",
    name: "Nehru Zoological Park",
    type: "Zoo and Family Park",
    category: "Parks",
    image: imageFor.nehruZoologicalPark,
    rating: "4.4",
    meta: "Bahadurpura | Zoo safari | Family outing",
    tip: "Go early, carry water, and use battery vehicles if visiting with children or elders.",
    lat: 17.3507,
    lng: 78.4516,
    distanceKm: 6.8,
    durationHours: 4,
    fee: 80,
    crowd: "High",
    safetyScore: 86,
    accessibility: "Battery vehicles and broad paths available in many zones.",
    bestTime: "Morning",
    tags: ["zoo", "family", "kids", "park", "safari"]
  },
  {
    slug: "shilparamam",
    name: "Shilparamam",
    type: "Arts, Crafts and Culture Village",
    category: "Markets",
    image: imageFor.shilparamam,
    rating: "4.4",
    meta: "Madhapur | Crafts | Food stalls | Performances",
    tip: "Best in the evening; check event schedules and keep cash for small craft stalls.",
    lat: 17.4526,
    lng: 78.3762,
    distanceKm: 13.5,
    durationHours: 2.5,
    fee: 60,
    crowd: "High",
    safetyScore: 88,
    accessibility: "Mostly open paths with some uneven craft-stall areas.",
    bestTime: "Evening",
    tags: ["crafts", "market", "culture", "madhapur", "shopping", "events"]
  },
  {
    slug: "inorbit-mall",
    name: "Inorbit Mall",
    type: "Shopping Mall",
    category: "Malls",
    image: imageFor.inorbitMall,
    rating: "4.5",
    meta: "Madhapur | Shopping | Food court | Cinema",
    tip: "Good for rain-safe shopping, restaurants, and movies; weekends get crowded after 5 PM.",
    lat: 17.4347,
    lng: 78.3866,
    distanceKm: 12.8,
    durationHours: 3,
    fee: 0,
    crowd: "High",
    safetyScore: 91,
    accessibility: "Elevators, escalators, parking, and wheelchair-friendly corridors.",
    bestTime: "Weekday afternoon",
    tags: ["mall", "shopping", "food court", "cinema", "madhapur", "rain safe"]
  },
  {
    slug: "forum-sujana-mall",
    name: "Forum Sujana Mall",
    type: "Shopping Mall",
    category: "Malls",
    image: imageFor.forumSujanaMall,
    rating: "4.4",
    meta: "Kukatpally | Shopping | Multiplex | Dining",
    tip: "Plan extra parking time on weekends and combine with nearby Kukatpally food spots.",
    lat: 17.4849,
    lng: 78.3898,
    distanceKm: 16.5,
    durationHours: 3,
    fee: 0,
    crowd: "High",
    safetyScore: 90,
    accessibility: "Mall access with elevators, ramps, and accessible washrooms.",
    bestTime: "Weekday evening",
    tags: ["mall", "shopping", "kukatpally", "multiplex", "restaurants"]
  },
  {
    slug: "sarath-city-capital-mall",
    name: "Sarath City Capital Mall",
    type: "Large Shopping Mall",
    category: "Malls",
    image: imageFor.sarathCityCapitalMall,
    rating: "4.5",
    meta: "Kondapur | Shopping | Kids zones | Dining",
    tip: "Good for families and groups; set a pickup point because the mall exits get busy.",
    lat: 17.4576,
    lng: 78.3636,
    distanceKm: 15.2,
    durationHours: 3.5,
    fee: 0,
    crowd: "Very high",
    safetyScore: 90,
    accessibility: "Large accessible mall with elevators and broad corridors.",
    bestTime: "Weekday afternoon",
    tags: ["mall", "kondapur", "shopping", "kids", "food", "cinema"]
  },
  {
    slug: "prasads-multiplex",
    name: "Prasads Multiplex",
    type: "Popular Theater and Entertainment",
    category: "Theaters",
    image: imageFor.prasadsMultiplex,
    rating: "4.4",
    meta: "Necklace Road | Movies | Gaming | Food",
    tip: "Pair a movie with Hussain Sagar or Tank Bund; pre-book seats for weekends.",
    lat: 17.4138,
    lng: 78.4653,
    distanceKm: 4.7,
    durationHours: 3,
    fee: 250,
    crowd: "High",
    safetyScore: 89,
    accessibility: "Mall-style entry with elevators and accessible seating options.",
    bestTime: "Evening",
    tags: ["theater", "cinema", "multiplex", "imax", "necklace road", "movies"]
  },
  {
    slug: "aaa-cinemas",
    name: "AAA Cinemas",
    type: "Premium Theater",
    category: "Theaters",
    image: imageFor.aaaCinemas,
    rating: "4.5",
    meta: "Ameerpet | Movies | Premium screens",
    tip: "Book early for big Telugu releases and use metro to avoid Ameerpet traffic.",
    lat: 17.4375,
    lng: 78.4483,
    distanceKm: 7.1,
    durationHours: 3,
    fee: 300,
    crowd: "High",
    safetyScore: 88,
    accessibility: "Elevator access and organized lobby movement.",
    bestTime: "Matinee",
    tags: ["theater", "cinema", "ameerpet", "telugu movies", "premium"]
  },
  {
    slug: "wonderla-hyderabad",
    name: "Wonderla Hyderabad",
    type: "Amusement and Water Park",
    category: "Theme Parks",
    image: imageFor.wonderlaHyderabad,
    rating: "4.5",
    meta: "Ravirala | Water rides | Family day trip",
    tip: "Carry swimwear, check ride maintenance updates, and arrive at opening time.",
    lat: 17.2176,
    lng: 78.5285,
    distanceKm: 28,
    durationHours: 7,
    fee: 1200,
    crowd: "High",
    safetyScore: 87,
    accessibility: "Managed park routes; ride access varies by attraction.",
    bestTime: "Morning",
    tags: ["wonderla", "theme park", "water park", "rides", "family", "kids"]
  },
  {
    slug: "gandipet-park",
    name: "Gandipet Lake Park",
    type: "Lake Park",
    category: "Lakes",
    image: imageFor.gandipetPark,
    rating: "4.3",
    meta: "Osman Sagar | Sunset | Picnic",
    tip: "Best for relaxed evenings; verify park timings before a long drive.",
    lat: 17.3919,
    lng: 78.3008,
    distanceKm: 20,
    durationHours: 2,
    fee: 50,
    crowd: "Moderate",
    safetyScore: 85,
    accessibility: "Open park paths; some areas may have uneven ground.",
    bestTime: "Sunset",
    tags: ["lake", "park", "gandipet", "sunset", "picnic", "family"]
  },
  {
    slug: "taj-falaknuma-palace",
    name: "Taj Falaknuma Palace",
    type: "Luxury Palace Hotel",
    category: "Resorts",
    image: imageFor.tajFalaknumaPalace,
    rating: "4.7",
    meta: "Falaknuma | Luxury dining | Palace experience",
    tip: "Reserve in advance for high tea or dining; dress codes and entry rules may apply.",
    lat: 17.3301,
    lng: 78.4675,
    distanceKm: 7.4,
    durationHours: 3,
    fee: 3500,
    crowd: "Low",
    safetyScore: 92,
    accessibility: "Managed luxury property access; confirm requirements while booking.",
    bestTime: "Evening",
    tags: ["palace", "luxury", "resort", "dining", "falaknuma", "experience"]
  }
];

const featuredFood: FoodSpot[] = [
  {
    name: "Paradise Biryani",
    category: "Biryani",
    area: "Secunderabad",
    costForTwo: 900,
    rating: 4.2,
    crowd: "High",
    openLate: true,
    distanceKm: 6.4,
    specialties: ["Hyderabadi biryani", "kebabs", "family seating"],
    safetyNote: "High-footfall main road area with cab access."
  },
  {
    name: "Nimrah Cafe",
    category: "Street food",
    area: "Charminar",
    costForTwo: 250,
    rating: 4.5,
    crowd: "Very high",
    openLate: true,
    distanceKm: 4.2,
    specialties: ["Irani chai", "Osmania biscuits", "Ramzan walk"],
    safetyNote: "Best with group travel at night; use marked pickup points."
  },
  {
    name: "Jubilee Hills Cafe Trail",
    category: "Cafe",
    area: "Jubilee Hills",
    costForTwo: 1400,
    rating: 4.4,
    crowd: "Moderate",
    openLate: false,
    distanceKm: 9.1,
    specialties: ["specialty coffee", "desserts", "work-friendly seating"],
    safetyNote: "Good parking and cab access."
  },
  {
    name: "Rooftop Dinner Circuit",
    category: "Rooftop",
    area: "HITEC City",
    costForTwo: 2600,
    rating: 4.3,
    crowd: "High",
    openLate: true,
    distanceKm: 14.8,
    specialties: ["skyline view", "mocktails", "date night"],
    safetyNote: "Pre-book tables and check return cab fares."
  },
  {
    name: "DLF Midnight Lane",
    category: "Midnight",
    area: "Gachibowli",
    costForTwo: 700,
    rating: 4.1,
    crowd: "High",
    openLate: true,
    distanceKm: 18.3,
    specialties: ["shawarma", "dosas", "tea", "late-night snacks"],
    safetyNote: "Busy tech corridor; avoid isolated side lanes."
  },
  {
    name: "Shah Ghouse",
    category: "Biryani",
    area: "Tolichowki",
    costForTwo: 800,
    rating: 4.3,
    crowd: "High",
    openLate: true,
    distanceKm: 8.7,
    specialties: ["biryani", "haleem", "kebabs", "late-night takeaway"],
    safetyNote: "Busy food stretch; prefer main-road pickup during late hours."
  },
  {
    name: "Cafe Niloufer",
    category: "Cafe",
    area: "Lakdikapul",
    costForTwo: 450,
    rating: 4.5,
    crowd: "Very high",
    openLate: true,
    distanceKm: 3.5,
    specialties: ["Irani chai", "Osmania biscuits", "bun maska"],
    safetyNote: "High-footfall central area; expect queues at peak tea time."
  },
  {
    name: "Chutneys",
    category: "South Indian",
    area: "Banjara Hills",
    costForTwo: 700,
    rating: 4.3,
    crowd: "High",
    openLate: false,
    distanceKm: 5.8,
    specialties: ["dosa", "idli", "chutney platters", "family dining"],
    safetyNote: "Good family-friendly dining zone with cab access."
  },
  {
    name: "Bawarchi",
    category: "Biryani",
    area: "RTC X Roads",
    costForTwo: 850,
    rating: 4.2,
    crowd: "Very high",
    openLate: true,
    distanceKm: 4.9,
    specialties: ["Hyderabadi biryani", "grill", "takeaway"],
    safetyNote: "Crowded main road; choose a clear pickup point."
  },
  {
    name: "Karachi Bakery",
    category: "Bakery",
    area: "Mozamjahi Market",
    costForTwo: 500,
    rating: 4.4,
    crowd: "High",
    openLate: false,
    distanceKm: 2.8,
    specialties: ["fruit biscuits", "plum cake", "souvenirs"],
    safetyNote: "Central market area; watch traffic while crossing."
  },
  {
    name: "Olive Bistro",
    category: "Fine dining",
    area: "Jubilee Hills",
    costForTwo: 3200,
    rating: 4.4,
    crowd: "Moderate",
    openLate: false,
    distanceKm: 10.2,
    specialties: ["Mediterranean", "lake view", "date night"],
    safetyNote: "Pre-book tables and confirm return cab availability."
  },
  {
    name: "Roastery Coffee House",
    category: "Cafe",
    area: "Banjara Hills",
    costForTwo: 1200,
    rating: 4.5,
    crowd: "Moderate",
    openLate: false,
    distanceKm: 6.2,
    specialties: ["specialty coffee", "desserts", "brunch"],
    safetyNote: "Quiet neighborhood access; use cab pickup after dark."
  }
];

const hyderabadRestaurantDirectory: FoodSpot[] = [
  { name: "Hotel Shadab", category: "Biryani", area: "Ghansi Bazaar", costForTwo: 900, rating: 4.4, crowd: "Very high", openLate: true, distanceKm: 4.1, specialties: ["mutton biryani", "haleem", "kebabs"], safetyNote: "Old City crowd; use main-road pickup points after dinner." },
  { name: "Cafe Bahar", category: "Biryani", area: "Basheerbagh", costForTwo: 800, rating: 4.4, crowd: "High", openLate: true, distanceKm: 2.9, specialties: ["Hyderabadi biryani", "Irani chai", "haleem"], safetyNote: "Central area with steady traffic and cab access." },
  { name: "Pista House", category: "Biryani", area: "Shalibanda", costForTwo: 850, rating: 4.3, crowd: "High", openLate: true, distanceKm: 4.8, specialties: ["haleem", "biryani", "bakery sweets"], safetyNote: "Busy landmark; confirm branch and pickup gate." },
  { name: "Meridian Restaurant", category: "Biryani", area: "Panjagutta", costForTwo: 800, rating: 4.2, crowd: "High", openLate: true, distanceKm: 5.1, specialties: ["mutton biryani", "grill", "takeaway"], safetyNote: "Main-road access; avoid stopping in traffic lanes." },
  { name: "Mehfil", category: "Biryani", area: "Narayanaguda", costForTwo: 700, rating: 4.2, crowd: "Very high", openLate: true, distanceKm: 3.9, specialties: ["biryani", "tandoori", "late-night meals"], safetyNote: "High-footfall stretch; share live location if visiting late." },
  { name: "Grand Hotel", category: "Biryani", area: "Abids", costForTwo: 750, rating: 4.1, crowd: "High", openLate: true, distanceKm: 2.7, specialties: ["biryani", "Irani cafe snacks", "bakery"], safetyNote: "Abids main-road location with regular cab access." },
  { name: "Hotel Rumaan", category: "Biryani", area: "Tolichowki", costForTwo: 750, rating: 4.2, crowd: "High", openLate: true, distanceKm: 8.4, specialties: ["biryani", "grill chicken", "kebabs"], safetyNote: "Popular late-night zone; choose a visible pickup spot." },
  { name: "Hotel Nayaab", category: "Biryani", area: "Chatta Bazaar", costForTwo: 700, rating: 4.3, crowd: "Very high", openLate: true, distanceKm: 3.8, specialties: ["nihari", "paya", "biryani"], safetyNote: "Best in groups for early breakfast or late dinner." },
  { name: "Sarvi Restaurant", category: "Biryani", area: "Banjara Hills", costForTwo: 950, rating: 4.2, crowd: "High", openLate: true, distanceKm: 5.6, specialties: ["haleem", "biryani", "kebabs"], safetyNote: "Easy cab access; parking is tight at peak hours." },
  { name: "Capital Multi Cuisine", category: "Biryani", area: "Malakpet", costForTwo: 850, rating: 4.1, crowd: "High", openLate: true, distanceKm: 5.2, specialties: ["biryani", "Chinese starters", "family meals"], safetyNote: "Prefer main entrance pickup during rush hours." },
  { name: "4 Seasons", category: "Biryani", area: "Tolichowki", costForTwo: 1200, rating: 4.2, crowd: "High", openLate: true, distanceKm: 8.6, specialties: ["mandi", "khabsa", "biryani"], safetyNote: "Busy food corridor with reliable cab availability." },
  { name: "Mandi @36", category: "Biryani", area: "Jubilee Hills", costForTwo: 1400, rating: 4.2, crowd: "High", openLate: true, distanceKm: 9.6, specialties: ["mandi", "grilled meat", "family platters"], safetyNote: "Pre-book for groups and confirm closing hours." },
  { name: "Mandilicious", category: "Biryani", area: "Madhapur", costForTwo: 1200, rating: 4.1, crowd: "High", openLate: true, distanceKm: 13.4, specialties: ["mandi", "shawaya", "Arabian rice"], safetyNote: "Tech-corridor access; late cabs are usually available." },
  { name: "Kritunga", category: "Biryani", area: "Madhapur", costForTwo: 1000, rating: 4.2, crowd: "High", openLate: true, distanceKm: 13.1, specialties: ["Rayalaseema biryani", "spicy curries", "ragimudda"], safetyNote: "Spicy food and busy queues; hydrate well." },
  { name: "Chaitanya Food Court", category: "Biryani", area: "Kukatpally", costForTwo: 900, rating: 4.1, crowd: "High", openLate: true, distanceKm: 16.2, specialties: ["fry piece biryani", "Andhra meals", "pulao"], safetyNote: "Mall-road traffic can be heavy; plan pickup outside the crowd." },
  { name: "Sri Kanya Comfort", category: "Biryani", area: "Kondapur", costForTwo: 1000, rating: 4.2, crowd: "High", openLate: true, distanceKm: 15.8, specialties: ["Andhra biryani", "prawns fry", "meals"], safetyNote: "Family-friendly but crowded on weekends." },
  { name: "The Nawaabs", category: "Biryani", area: "Gachibowli", costForTwo: 1200, rating: 4.2, crowd: "High", openLate: true, distanceKm: 18.2, specialties: ["biryani", "kebabs", "North Indian"], safetyNote: "Use cab pickup from the main approach road." },
  { name: "Biryaniwalla & Co", category: "Biryani", area: "Banjara Hills", costForTwo: 1100, rating: 4.1, crowd: "Moderate", openLate: true, distanceKm: 6.4, specialties: ["dum biryani", "kebabs", "family packs"], safetyNote: "Good for takeaway; confirm branch before travel." },
  { name: "Behrouz Biryani", category: "Biryani", area: "Multiple cloud kitchens", costForTwo: 900, rating: 4.0, crowd: "Low", openLate: true, distanceKm: 7.5, specialties: ["delivery biryani", "kebabs", "desserts"], safetyNote: "Delivery-first option; verify kitchen coverage by location." },
  { name: "Potful", category: "Biryani", area: "HITEC City", costForTwo: 900, rating: 4.1, crowd: "Moderate", openLate: true, distanceKm: 14.3, specialties: ["claypot biryani", "meal boxes", "delivery"], safetyNote: "Best for delivery or quick pickup." },
  { name: "MRCB", category: "Biryani", area: "Kondapur", costForTwo: 1200, rating: 4.2, crowd: "High", openLate: true, distanceKm: 15.4, specialties: ["Mughlai", "biryani", "kebabs"], safetyNote: "Book ahead for weekend dinner." },
  { name: "Shahi Dastarkhwan", category: "Biryani", area: "Lakdikapul", costForTwo: 850, rating: 4.1, crowd: "High", openLate: true, distanceKm: 3.2, specialties: ["biryani", "mutton dishes", "takeaway"], safetyNote: "Central traffic zone; use a clear pickup landmark." },
  { name: "Mandar Restaurant", category: "Biryani", area: "Himayatnagar", costForTwo: 800, rating: 4.0, crowd: "Moderate", openLate: true, distanceKm: 3.4, specialties: ["biryani", "North Indian", "family dining"], safetyNote: "Main-road access is safer after dark." },
  { name: "Rayalaseema Ruchulu", category: "South Indian", area: "Lakdikapul", costForTwo: 1400, rating: 4.3, crowd: "High", openLate: false, distanceKm: 3.0, specialties: ["Rayalaseema meals", "ragi sangati", "natukodi"], safetyNote: "Spicy regional food; reserve for groups." },
  { name: "Ulavacharu", category: "South Indian", area: "Jubilee Hills", costForTwo: 1600, rating: 4.3, crowd: "High", openLate: false, distanceKm: 9.2, specialties: ["Andhra cuisine", "pulao", "regional curries"], safetyNote: "Good parking and cab access." },
  { name: "The Spicy Venue", category: "South Indian", area: "Jubilee Hills", costForTwo: 1500, rating: 4.3, crowd: "High", openLate: false, distanceKm: 8.9, specialties: ["apricot delight", "Andhra meals", "biryani"], safetyNote: "Reserve ahead for peak lunch and dinner." },
  { name: "Simply South", category: "South Indian", area: "Film Nagar", costForTwo: 1700, rating: 4.4, crowd: "Moderate", openLate: false, distanceKm: 9.7, specialties: ["Telugu cuisine", "Tamil cuisine", "Kerala dishes"], safetyNote: "Quiet dining area with good cab access." },
  { name: "AnTeRa", category: "South Indian", area: "Jubilee Hills", costForTwo: 1700, rating: 4.4, crowd: "High", openLate: true, distanceKm: 9.4, specialties: ["Telugu specials", "regional thalis", "cocktails"], safetyNote: "Busy nightlife road; pre-book cabs." },
  { name: "Minerva Coffee Shop", category: "South Indian", area: "Himayatnagar", costForTwo: 700, rating: 4.2, crowd: "High", openLate: false, distanceKm: 3.1, specialties: ["idli", "dosa", "filter coffee"], safetyNote: "Family-friendly and central." },
  { name: "Taj Mahal Hotel", category: "South Indian", area: "Abids", costForTwo: 600, rating: 4.2, crowd: "High", openLate: false, distanceKm: 2.4, specialties: ["tiffins", "meals", "filter coffee"], safetyNote: "Old commercial district; watch traffic crossings." },
  { name: "Kamat Hotel", category: "South Indian", area: "Nampally", costForTwo: 600, rating: 4.1, crowd: "Moderate", openLate: false, distanceKm: 2.5, specialties: ["South Indian meals", "idli", "vada"], safetyNote: "Transit-friendly area; keep bags close." },
  { name: "Ram Ki Bandi", category: "Street food", area: "Nampally", costForTwo: 250, rating: 4.4, crowd: "Very high", openLate: true, distanceKm: 2.2, specialties: ["dosa", "cheese dosa", "late-night tiffins"], safetyNote: "Best with friends; expect street crowd late night." },
  { name: "Govind Dosa", category: "Street food", area: "Charminar", costForTwo: 250, rating: 4.3, crowd: "Very high", openLate: true, distanceKm: 4.0, specialties: ["butter dosa", "street tiffins", "idli"], safetyNote: "Old City lanes; travel light and use visible pickup points." },
  { name: "Pragati Tiffins", category: "South Indian", area: "Koti", costForTwo: 250, rating: 4.3, crowd: "Very high", openLate: false, distanceKm: 2.1, specialties: ["idli", "upma", "dosa"], safetyNote: "Very crowded counter; keep valuables secure." },
  { name: "Panchakattu Dosa", category: "South Indian", area: "KPHB", costForTwo: 400, rating: 4.2, crowd: "High", openLate: false, distanceKm: 16.1, specialties: ["ghee karam dosa", "idli", "filter coffee"], safetyNote: "Family crowd; weekends are busy." },
  { name: "Taaza Kitchen", category: "South Indian", area: "Madhapur", costForTwo: 450, rating: 4.3, crowd: "High", openLate: false, distanceKm: 13.2, specialties: ["dosa", "idli", "filter coffee"], safetyNote: "Good breakfast option; queues move fast." },
  { name: "Swachh", category: "South Indian", area: "Gachibowli", costForTwo: 500, rating: 4.2, crowd: "High", openLate: false, distanceKm: 17.4, specialties: ["tiffins", "meals", "coffee"], safetyNote: "Tech-area crowd; use main parking." },
  { name: "Poorna Tiffins", category: "South Indian", area: "Krishna Nagar", costForTwo: 300, rating: 4.2, crowd: "High", openLate: false, distanceKm: 7.4, specialties: ["dosa", "vada", "idli"], safetyNote: "Narrow lanes; two-wheeler access is easier." },
  { name: "Varalakshmi Tiffins", category: "South Indian", area: "Gachibowli", costForTwo: 450, rating: 4.1, crowd: "High", openLate: false, distanceKm: 17.6, specialties: ["ghee karam idli", "dosa", "filter coffee"], safetyNote: "Use main-road pickup at night." },
  { name: "Ishtaa", category: "South Indian", area: "HITEC City", costForTwo: 800, rating: 4.3, crowd: "Moderate", openLate: false, distanceKm: 14.6, specialties: ["modern tiffins", "filter coffee", "brunch"], safetyNote: "Calmer option for family breakfast." },
  { name: "Udipi's Upahar", category: "South Indian", area: "Ameerpet", costForTwo: 450, rating: 4.0, crowd: "High", openLate: false, distanceKm: 6.5, specialties: ["idli", "dosa", "meals"], safetyNote: "Ameerpet traffic is heavy; use metro if possible." },
  { name: "Hampi", category: "South Indian", area: "Banjara Hills", costForTwo: 1400, rating: 4.3, crowd: "Moderate", openLate: false, distanceKm: 6.3, specialties: ["Karnataka cuisine", "regional thali", "dosas"], safetyNote: "Good cab access and family seating." },
  { name: "Gokul Chaat", category: "Street food", area: "Koti", costForTwo: 250, rating: 4.2, crowd: "Very high", openLate: false, distanceKm: 2.0, specialties: ["chaat", "pani puri", "dahi puri"], safetyNote: "Very crowded; keep bags in front." },
  { name: "Maharaja Chaat", category: "Street food", area: "Madhapur", costForTwo: 300, rating: 4.1, crowd: "High", openLate: false, distanceKm: 13.3, specialties: ["chaat", "pav bhaji", "snacks"], safetyNote: "Good evening snack stop with main-road access." },
  { name: "Mayur Pan House", category: "Street food", area: "Abids", costForTwo: 200, rating: 4.2, crowd: "High", openLate: true, distanceKm: 2.6, specialties: ["paan", "falooda", "street snacks"], safetyNote: "Busy late evening spot; use nearby pickup landmarks." },
  { name: "Siddique Kabab Centre", category: "Street food", area: "Kondapur", costForTwo: 600, rating: 4.1, crowd: "High", openLate: true, distanceKm: 15.5, specialties: ["kebabs", "rolls", "grills"], safetyNote: "Late-night crowd; prefer main-road pickup." },
  { name: "Al Akbar Fast Food", category: "Street food", area: "Tolichowki", costForTwo: 500, rating: 4.1, crowd: "High", openLate: true, distanceKm: 8.8, specialties: ["shawarma", "grill chicken", "rolls"], safetyNote: "Popular late-night stretch with heavy traffic." },
  { name: "Yousuf Tekri Food Court", category: "Street food", area: "Tolichowki", costForTwo: 700, rating: 4.1, crowd: "Very high", openLate: true, distanceKm: 8.9, specialties: ["kebabs", "mandi", "desserts"], safetyNote: "Go with a group during late hours." },
  { name: "AM-PM Food Court", category: "Midnight", area: "Madhapur", costForTwo: 600, rating: 4.0, crowd: "High", openLate: true, distanceKm: 13.6, specialties: ["shawarma", "tea", "fast food"], safetyNote: "Use main-road pickup and avoid isolated lanes." },
  { name: "The Joint Al Mandi", category: "Midnight", area: "Madhapur", costForTwo: 1000, rating: 4.1, crowd: "High", openLate: true, distanceKm: 13.8, specialties: ["mandi", "grills", "rice platters"], safetyNote: "Good group option; check current closing time." },
  { name: "Shawarma Corner", category: "Midnight", area: "Gachibowli", costForTwo: 450, rating: 4.0, crowd: "High", openLate: true, distanceKm: 18.0, specialties: ["shawarma", "fries", "tea"], safetyNote: "Tech-corridor access is active late night." },
  { name: "Famous Ice Cream", category: "Street food", area: "Mozamjahi Market", costForTwo: 250, rating: 4.2, crowd: "High", openLate: true, distanceKm: 2.7, specialties: ["handmade ice cream", "seasonal flavors", "desserts"], safetyNote: "Old market area; watch traffic and crowds." },
  { name: "Subhan Bakery", category: "Bakery", area: "Nampally", costForTwo: 350, rating: 4.4, crowd: "High", openLate: false, distanceKm: 2.3, specialties: ["Osmania biscuits", "dum ke roat", "plum cake"], safetyNote: "Busy counter; park legally nearby." },
  { name: "Almond House", category: "Bakery", area: "Banjara Hills", costForTwo: 600, rating: 4.4, crowd: "Moderate", openLate: false, distanceKm: 6.2, specialties: ["sweets", "baklava", "snack boxes"], safetyNote: "Good for family shopping and gifting." },
  { name: "Labonel", category: "Bakery", area: "Banjara Hills", costForTwo: 900, rating: 4.4, crowd: "Moderate", openLate: false, distanceKm: 6.4, specialties: ["cakes", "brownies", "desserts"], safetyNote: "Confirm pickup slot for cakes." },
  { name: "Concu", category: "Bakery", area: "Jubilee Hills", costForTwo: 1200, rating: 4.5, crowd: "High", openLate: false, distanceKm: 9.0, specialties: ["pastries", "macarons", "desserts"], safetyNote: "Popular cafe area; reserve if dining in." },
  { name: "Feranoz", category: "Bakery", area: "Banjara Hills", costForTwo: 1200, rating: 4.3, crowd: "Moderate", openLate: false, distanceKm: 6.1, specialties: ["patisserie", "cakes", "coffee"], safetyNote: "Use cab pickup on the main road." },
  { name: "Theobroma", category: "Bakery", area: "HITEC City", costForTwo: 700, rating: 4.2, crowd: "Moderate", openLate: false, distanceKm: 14.5, specialties: ["brownies", "cakes", "sandwiches"], safetyNote: "Good for quick dessert stops." },
  { name: "Vac's Pastries", category: "Bakery", area: "Secunderabad", costForTwo: 500, rating: 4.2, crowd: "Moderate", openLate: false, distanceKm: 7.2, specialties: ["pastries", "puffs", "cakes"], safetyNote: "Neighborhood bakery; check parking before pickup." },
  { name: "Dadu's", category: "Bakery", area: "Banjara Hills", costForTwo: 800, rating: 4.2, crowd: "High", openLate: false, distanceKm: 6.0, specialties: ["sweets", "chaat", "snacks"], safetyNote: "Family-friendly with busy festive queues." },
  { name: "Cream Stone", category: "Bakery", area: "Jubilee Hills", costForTwo: 550, rating: 4.3, crowd: "High", openLate: true, distanceKm: 8.8, specialties: ["ice cream", "desserts", "late-night sweets"], safetyNote: "Late dessert crowd; choose visible pickup spots." },
  { name: "Funnel Hill Creamery", category: "Bakery", area: "Jubilee Hills", costForTwo: 700, rating: 4.2, crowd: "Moderate", openLate: true, distanceKm: 9.1, specialties: ["ice cream", "waffles", "desserts"], safetyNote: "Good late dessert option; confirm closing." },
  { name: "Roast 24 Seven", category: "Cafe", area: "Gachibowli", costForTwo: 1400, rating: 4.4, crowd: "High", openLate: true, distanceKm: 17.8, specialties: ["coffee", "desserts", "all-day dining"], safetyNote: "Active tech corridor; late cabs are available." },
  { name: "Autumn Leaf Cafe", category: "Cafe", area: "Jubilee Hills", costForTwo: 1600, rating: 4.4, crowd: "High", openLate: false, distanceKm: 8.6, specialties: ["brunch", "coffee", "outdoor seating"], safetyNote: "Reserve outdoor tables during pleasant weather." },
  { name: "The Hole in the Wall Cafe", category: "Cafe", area: "Jubilee Hills", costForTwo: 1200, rating: 4.3, crowd: "High", openLate: false, distanceKm: 9.0, specialties: ["breakfast", "pancakes", "coffee"], safetyNote: "Expect weekend brunch queues." },
  { name: "Lamakaan Cafe", category: "Cafe", area: "Banjara Hills", costForTwo: 300, rating: 4.4, crowd: "Moderate", openLate: false, distanceKm: 5.7, specialties: ["chai", "samosa", "cultural events"], safetyNote: "Community space; check event timings." },
  { name: "Heart Cup Coffee", category: "Cafe", area: "Kondapur", costForTwo: 1500, rating: 4.2, crowd: "High", openLate: true, distanceKm: 15.7, specialties: ["coffee", "live music", "pub food"], safetyNote: "Nightlife crowd; book cabs before closing." },
  { name: "Theory Cafe", category: "Cafe", area: "Jubilee Hills", costForTwo: 1700, rating: 4.3, crowd: "Moderate", openLate: false, distanceKm: 8.9, specialties: ["coffee", "continental", "desserts"], safetyNote: "Quiet cafe; confirm table availability." },
  { name: "Driven Cafe", category: "Cafe", area: "Jubilee Hills", costForTwo: 1200, rating: 4.2, crowd: "Moderate", openLate: true, distanceKm: 9.5, specialties: ["coffee", "bike theme", "quick bites"], safetyNote: "Good main-road access." },
  { name: "Last House Coffee", category: "Cafe", area: "Jubilee Hills", costForTwo: 1000, rating: 4.2, crowd: "Moderate", openLate: false, distanceKm: 9.3, specialties: ["coffee", "desserts", "quiet seating"], safetyNote: "Use cab pickup near the main gate." },
  { name: "Ofen", category: "Cafe", area: "Banjara Hills", costForTwo: 1000, rating: 4.2, crowd: "Moderate", openLate: false, distanceKm: 6.1, specialties: ["bakery", "sandwiches", "coffee"], safetyNote: "Good daytime cafe with family crowd." },
  { name: "Good Vibes Only Cafe", category: "Cafe", area: "Madhapur", costForTwo: 900, rating: 4.1, crowd: "Moderate", openLate: false, distanceKm: 13.7, specialties: ["coffee", "snacks", "work seating"], safetyNote: "Tech-area traffic peaks at office hours." },
  { name: "Terrassen Cafe", category: "Cafe", area: "Banjara Hills", costForTwo: 1000, rating: 4.2, crowd: "Moderate", openLate: false, distanceKm: 6.5, specialties: ["vegan food", "coffee", "brunch"], safetyNote: "Quiet lanes; use cab pickup after dark." },
  { name: "Adaa", category: "Fine dining", area: "Falaknuma", costForTwo: 7000, rating: 4.6, crowd: "Low", openLate: false, distanceKm: 7.4, specialties: ["Hyderabadi fine dining", "palace dining", "tasting menu"], safetyNote: "Reservation-led palace access; verify dress code." },
  { name: "Jewel of Nizam", category: "Fine dining", area: "Gandipet", costForTwo: 7000, rating: 4.7, crowd: "Moderate", openLate: false, distanceKm: 20.5, specialties: ["royal Indian", "lake view", "kebabs"], safetyNote: "Reserve and arrange return cab before dinner." },
  { name: "Dum Pukht Begum's", category: "Fine dining", area: "HITEC City", costForTwo: 6000, rating: 4.6, crowd: "Moderate", openLate: false, distanceKm: 14.2, specialties: ["Awadhi", "dum cooking", "kebabs"], safetyNote: "Hotel dining with secure access." },
  { name: "Dakshin", category: "Fine dining", area: "Begumpet", costForTwo: 4500, rating: 4.6, crowd: "Moderate", openLate: false, distanceKm: 6.5, specialties: ["South Indian fine dining", "seafood", "thali"], safetyNote: "Hotel property access; book ahead." },
  { name: "Bidri", category: "Fine dining", area: "Tank Bund", costForTwo: 3500, rating: 4.5, crowd: "Moderate", openLate: false, distanceKm: 5.2, specialties: ["Hyderabadi cuisine", "kebabs", "biryani"], safetyNote: "Secure hotel dining and easy cab pickup." },
  { name: "Seasonal Tastes", category: "Fine dining", area: "HITEC City", costForTwo: 3000, rating: 4.4, crowd: "High", openLate: false, distanceKm: 14.0, specialties: ["buffet", "global cuisine", "desserts"], safetyNote: "Hotel dining with parking and valet." },
  { name: "Amara", category: "Fine dining", area: "Gachibowli", costForTwo: 3500, rating: 4.5, crowd: "Moderate", openLate: false, distanceKm: 18.4, specialties: ["buffet", "Indian", "global cuisine"], safetyNote: "Hotel access; arrange return cab for late dinners." },
  { name: "Tre-Forni", category: "Fine dining", area: "Banjara Hills", costForTwo: 4000, rating: 4.4, crowd: "Moderate", openLate: false, distanceKm: 6.0, specialties: ["Italian", "wood-fired pizza", "wine dinner"], safetyNote: "Hotel dining with secure parking." },
  { name: "Mekong", category: "Fine dining", area: "Begumpet", costForTwo: 4200, rating: 4.5, crowd: "Moderate", openLate: false, distanceKm: 6.7, specialties: ["Pan Asian", "dim sum", "noodles"], safetyNote: "Hotel property with easy pickup." },
  { name: "Zega", category: "Fine dining", area: "Gachibowli", costForTwo: 4500, rating: 4.4, crowd: "High", openLate: true, distanceKm: 18.0, specialties: ["Asian", "sushi", "nightlife"], safetyNote: "Book cabs before closing during weekends." },
  { name: "Kanak", category: "Fine dining", area: "HITEC City", costForTwo: 3500, rating: 4.4, crowd: "Moderate", openLate: false, distanceKm: 14.4, specialties: ["Indian", "kebabs", "curries"], safetyNote: "Hotel access and valet available." },
  { name: "Yi Jing", category: "Fine dining", area: "HITEC City", costForTwo: 4500, rating: 4.5, crowd: "Moderate", openLate: false, distanceKm: 14.1, specialties: ["Chinese", "dim sum", "duck"], safetyNote: "Reserve ahead for dinner service." },
  { name: "Okra", category: "Fine dining", area: "Tank Bund", costForTwo: 3000, rating: 4.3, crowd: "Moderate", openLate: false, distanceKm: 5.0, specialties: ["buffet", "Indian", "continental"], safetyNote: "Hotel dining near Tank Bund traffic." },
  { name: "Deccan Kitchen", category: "Fine dining", area: "HITEC City", costForTwo: 3200, rating: 4.3, crowd: "Moderate", openLate: false, distanceKm: 14.0, specialties: ["Telangana cuisine", "modern Indian", "thali"], safetyNote: "Hotel property access and valet." },
  { name: "Punjab Grill", category: "Fine dining", area: "Jubilee Hills", costForTwo: 2800, rating: 4.3, crowd: "High", openLate: false, distanceKm: 9.2, specialties: ["North Indian", "kebabs", "curries"], safetyNote: "Popular dinner spot; reserve ahead." },
  { name: "Exotica", category: "Rooftop", area: "Banjara Hills", costForTwo: 2200, rating: 4.3, crowd: "High", openLate: true, distanceKm: 6.1, specialties: ["rooftop dining", "North Indian", "kebabs"], safetyNote: "Use valet and pre-book weekend tables." },
  { name: "Tansen", category: "Fine dining", area: "Financial District", costForTwo: 3000, rating: 4.4, crowd: "High", openLate: true, distanceKm: 20.0, specialties: ["Indian", "live music", "kebabs"], safetyNote: "Late-night return cabs can surge; plan early." },
  { name: "Tatva", category: "Fine dining", area: "Jubilee Hills", costForTwo: 2200, rating: 4.3, crowd: "Moderate", openLate: false, distanceKm: 9.3, specialties: ["vegetarian", "North Indian", "continental"], safetyNote: "Good family dining; reserve on weekends." },
  { name: "Burma Burma", category: "Fine dining", area: "Knowledge City", costForTwo: 2000, rating: 4.4, crowd: "High", openLate: false, distanceKm: 14.8, specialties: ["Burmese", "vegetarian", "tea leaf salad"], safetyNote: "Crowded mall district; book ahead." },
  { name: "Farzi Cafe", category: "Fine dining", area: "Jubilee Hills", costForTwo: 2500, rating: 4.2, crowd: "High", openLate: true, distanceKm: 9.1, specialties: ["modern Indian", "small plates", "mocktails"], safetyNote: "Nightlife crowd; confirm table and pickup." },
  { name: "Little Italy", category: "Fine dining", area: "Jubilee Hills", costForTwo: 1800, rating: 4.2, crowd: "Moderate", openLate: false, distanceKm: 9.1, specialties: ["Italian", "vegetarian", "pizza"], safetyNote: "Family-friendly; main-road cab access." },
  { name: "Aish", category: "Fine dining", area: "Banjara Hills", costForTwo: 3500, rating: 4.4, crowd: "Moderate", openLate: false, distanceKm: 6.2, specialties: ["Hyderabadi", "Indian", "hotel dining"], safetyNote: "Hotel access and managed pickup." },
  { name: "Altitude Lounge Bar", category: "Rooftop", area: "Tank Bund", costForTwo: 3000, rating: 4.3, crowd: "High", openLate: true, distanceKm: 5.1, specialties: ["lake view", "rooftop", "small plates"], safetyNote: "Book return cab before closing on weekends." },
  { name: "Over The Moon", category: "Rooftop", area: "Jubilee Hills", costForTwo: 2800, rating: 4.2, crowd: "High", openLate: true, distanceKm: 9.4, specialties: ["rooftop", "continental", "nightlife"], safetyNote: "Nightlife area; use valet and cabs." },
  { name: "Air Live", category: "Rooftop", area: "Jubilee Hills", costForTwo: 2500, rating: 4.1, crowd: "Very high", openLate: true, distanceKm: 9.2, specialties: ["live music", "rooftop", "pub food"], safetyNote: "Crowded weekends; travel in groups." },
  { name: "Amnesia Lounge Bar", category: "Rooftop", area: "Jubilee Hills", costForTwo: 2600, rating: 4.1, crowd: "High", openLate: true, distanceKm: 9.0, specialties: ["rooftop", "DJ nights", "finger food"], safetyNote: "Arrange return transport before late-night closure." },
  { name: "Prost Brewpub", category: "Rooftop", area: "Jubilee Hills", costForTwo: 2300, rating: 4.2, crowd: "High", openLate: true, distanceKm: 8.8, specialties: ["brewpub", "pizza", "pub food"], safetyNote: "Use cab transport after nightlife hours." },
  { name: "Zero40 Brewing", category: "Rooftop", area: "Jubilee Hills", costForTwo: 2400, rating: 4.2, crowd: "High", openLate: true, distanceKm: 9.0, specialties: ["brewpub", "continental", "pub food"], safetyNote: "Busy road; book cabs early." },
  { name: "Broadway The Brewery", category: "Rooftop", area: "Jubilee Hills", costForTwo: 2500, rating: 4.2, crowd: "High", openLate: true, distanceKm: 9.5, specialties: ["brewery", "global plates", "live events"], safetyNote: "Weekend surge pricing is common." },
  { name: "MOB Belgian Beer House", category: "Rooftop", area: "Jubilee Hills", costForTwo: 2500, rating: 4.1, crowd: "Moderate", openLate: true, distanceKm: 9.3, specialties: ["European pub food", "sharing plates", "nightlife"], safetyNote: "Use valet and verified cabs." },
  { name: "Forge Breu Hous", category: "Rooftop", area: "Jubilee Hills", costForTwo: 2500, rating: 4.1, crowd: "High", openLate: true, distanceKm: 9.4, specialties: ["brewery", "grills", "music"], safetyNote: "Plan return transport before midnight." },
  { name: "Fat Pigeon", category: "Rooftop", area: "Jubilee Hills", costForTwo: 2400, rating: 4.1, crowd: "High", openLate: true, distanceKm: 9.1, specialties: ["rooftop", "music", "finger food"], safetyNote: "Nightlife crowd; stay with your group." },
  { name: "Prism Club Kitchen", category: "Rooftop", area: "Financial District", costForTwo: 3000, rating: 4.1, crowd: "High", openLate: true, distanceKm: 20.2, specialties: ["club dining", "Asian plates", "nightlife"], safetyNote: "Far from city center; pre-plan return cab." },
  { name: "Jonathan's Kitchen", category: "Fine dining", area: "Gachibowli", costForTwo: 3000, rating: 4.3, crowd: "Moderate", openLate: true, distanceKm: 18.6, specialties: ["global cuisine", "sushi", "hotel dining"], safetyNote: "Hotel access with parking." },
  { name: "Jonathan's Bakehouse", category: "Bakery", area: "Gachibowli", costForTwo: 900, rating: 4.2, crowd: "Moderate", openLate: false, distanceKm: 18.6, specialties: ["pastries", "breads", "coffee"], safetyNote: "Good pickup inside hotel property." },
  { name: "Hard Rock Cafe", category: "Rooftop", area: "Banjara Hills", costForTwo: 2500, rating: 4.2, crowd: "High", openLate: true, distanceKm: 5.8, specialties: ["burgers", "live music", "American"], safetyNote: "Nightlife crowd; use verified cabs." },
  { name: "Chili's", category: "Fine dining", area: "Banjara Hills", costForTwo: 2200, rating: 4.1, crowd: "High", openLate: true, distanceKm: 6.1, specialties: ["Tex-Mex", "burgers", "mocktails"], safetyNote: "Mall and main-road access is convenient." },
  { name: "Haiku", category: "Fine dining", area: "Banjara Hills", costForTwo: 2200, rating: 4.3, crowd: "Moderate", openLate: false, distanceKm: 6.4, specialties: ["Asian", "sushi", "ramen"], safetyNote: "Quiet dining area; book ahead." },
  { name: "Hashi", category: "Fine dining", area: "Jubilee Hills", costForTwo: 2400, rating: 4.2, crowd: "Moderate", openLate: false, distanceKm: 9.2, specialties: ["Japanese", "sushi", "ramen"], safetyNote: "Use main-road pickup after dinner." },
  { name: "Haiku Hitech City", category: "Fine dining", area: "HITEC City", costForTwo: 2200, rating: 4.2, crowd: "Moderate", openLate: false, distanceKm: 14.4, specialties: ["Asian", "sushi", "bowls"], safetyNote: "Tech-area traffic peaks during office exits." },
  { name: "Nanking", category: "Fine dining", area: "Secunderabad", costForTwo: 1600, rating: 4.1, crowd: "Moderate", openLate: false, distanceKm: 7.0, specialties: ["Chinese", "soups", "noodles"], safetyNote: "Family-friendly; parking can be tight." },
  { name: "Alex's Kitchen", category: "Fine dining", area: "Secunderabad", costForTwo: 1200, rating: 4.1, crowd: "Moderate", openLate: false, distanceKm: 7.4, specialties: ["Chinese", "Indian Chinese", "soups"], safetyNote: "Neighborhood dining; use cab pickup on main road." },
  { name: "Golden Dragon", category: "Fine dining", area: "Basheerbagh", costForTwo: 1800, rating: 4.1, crowd: "Moderate", openLate: false, distanceKm: 2.8, specialties: ["Chinese", "seafood", "noodles"], safetyNote: "Central access; traffic can be dense." },
  { name: "Ohri's Jiva Imperia", category: "Fine dining", area: "Begumpet", costForTwo: 1800, rating: 4.2, crowd: "High", openLate: false, distanceKm: 6.4, specialties: ["vegetarian buffet", "North Indian", "desserts"], safetyNote: "Family crowd; reserve for weekends." },
  { name: "Ohri's 70mm", category: "Fine dining", area: "Necklace Road", costForTwo: 1700, rating: 4.1, crowd: "High", openLate: false, distanceKm: 4.8, specialties: ["themed dining", "Indian", "buffet"], safetyNote: "Pair with Tank Bund but plan traffic." },
  { name: "Sahib Sindh Sultan", category: "Fine dining", area: "Banjara Hills", costForTwo: 2200, rating: 4.2, crowd: "Moderate", openLate: false, distanceKm: 6.2, specialties: ["North Indian", "railway theme", "kebabs"], safetyNote: "Mall-style access and parking." },
  { name: "Barbeque Nation", category: "Fine dining", area: "Banjara Hills", costForTwo: 1800, rating: 4.2, crowd: "High", openLate: false, distanceKm: 6.0, specialties: ["grill buffet", "desserts", "family dining"], safetyNote: "Reserve ahead for groups." },
  { name: "Absolute Barbecues", category: "Fine dining", area: "Jubilee Hills", costForTwo: 1900, rating: 4.2, crowd: "High", openLate: false, distanceKm: 9.0, specialties: ["grill buffet", "wish grill", "desserts"], safetyNote: "Large groups should book early." },
  { name: "Flechazo", category: "Fine dining", area: "Madhapur", costForTwo: 1800, rating: 4.2, crowd: "High", openLate: false, distanceKm: 13.5, specialties: ["Mediterranean buffet", "Asian", "desserts"], safetyNote: "Tech-area parking can fill quickly." },
  { name: "Flechazo Gachibowli", category: "Fine dining", area: "Gachibowli", costForTwo: 1800, rating: 4.2, crowd: "High", openLate: false, distanceKm: 18.0, specialties: ["buffet", "grills", "desserts"], safetyNote: "Good group dining; pre-book slots." },
  { name: "The Fisherman's Wharf", category: "Fine dining", area: "Financial District", costForTwo: 2500, rating: 4.3, crowd: "High", openLate: true, distanceKm: 20.1, specialties: ["Goan seafood", "live music", "outdoor seating"], safetyNote: "Far-west location; arrange return cab." },
  { name: "By The Bottle", category: "Rooftop", area: "Jubilee Hills", costForTwo: 2400, rating: 4.1, crowd: "High", openLate: true, distanceKm: 9.0, specialties: ["rooftop", "finger food", "music"], safetyNote: "Nightlife traffic; use verified pickup." },
  { name: "Kismet", category: "Rooftop", area: "Somajiguda", costForTwo: 3500, rating: 4.2, crowd: "High", openLate: true, distanceKm: 5.2, specialties: ["club dining", "small plates", "music"], safetyNote: "Plan transport before late-night closure." },
  { name: "10 Downing Street", category: "Rooftop", area: "Begumpet", costForTwo: 2200, rating: 4.1, crowd: "High", openLate: true, distanceKm: 6.1, specialties: ["pub food", "karaoke", "continental"], safetyNote: "Use cab pickup from the main road." }
];

export const food: FoodSpot[] = [...featuredFood, ...hyderabadRestaurantDirectory];

export const events: EventItem[] = [
  { title: "Ramzan Food Streets", date: "Seasonal evenings", type: "Food festival", venue: "Charminar", price: "Pay per dish" },
  { title: "Bonalu Processions", date: "Ashada season", type: "Festival", venue: "Old City temples", price: "Free" },
  { title: "Bathukamma Celebrations", date: "Sep-Oct", type: "Culture", venue: "Tank Bund", price: "Free" },
  { title: "Shilparamam Craft Bazaar", date: "Weekly", type: "Exhibition", venue: "Madhapur", price: "INR 60" }
];

export const metroRoutes: MetroRoute[] = [
  { from: "HITEC City", to: "Charminar", line: "Blue + Green", interchange: "Ameerpet, MG Bus Station", duration: "55-70 min", fare: "INR 60" },
  { from: "Secunderabad", to: "Hussain Sagar", line: "Blue", interchange: "None", duration: "15-25 min", fare: "INR 20-35" },
  { from: "Jubilee Hills", to: "Golconda", line: "Blue + cab", interchange: "Peddamma Gudi", duration: "35-50 min", fare: "INR 120-240" }
];

export const emergencyContacts = [
  { label: "Police", value: "100" },
  { label: "Women safety", value: "1091" },
  { label: "Ambulance", value: "108" },
  { label: "Tourist helpline", value: "1363" }
];

export const highlights = [
  "AR heritage previews",
  "Women safety ratings",
  "QR tourism guide",
  "Telugu, Hindi, English",
  "Offline PWA mode",
  "AI crowd prediction",
  "Cab fare estimates",
  "Weather intelligence"
];
